name: CI

on:
  push:
    branches: [ main, release,  ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     - name: Flutter action
       uses: subosito/flutter-action@v1.5.3
     - run: flutter pub get
     - run: flutter test
